
- hosts: "Managed_Node1"
  tasks:
  - name: Deploy Docker and run httpd container
  hosts: all
  become: true
  tasks:
    - name: Install Docker
      yum:
        name: docker
        state: present

    - name: Start and enable Docker service
      systemd:
        name: docker
        state: started
        enabled: yes

    - name: Install
      command: pip install docker-py

    - name: Pull httpd server image from Docker Hub
      docker_image:
        name: httpd
        source: pull

    - name: Create Persistent Volume
      docker_volume:
        name: httpd_volume
        state: present

    - name: Run httpd container
      docker_container:
        name: httpd_container
        image: httpd
        state: started
        restart_policy: always
        volumes:
          - httpd_volume:/usr/local/apache2/htdocs
        ports:
          - "80:80"
